public class UniPOS
{
    public string DATE { get; set; }
    public string TIME { get; set; }
    public string TRANSACTION_STATUS { get; set; }
    public string TRANSACTION_TYPE { get; set; }
    public string TRANSACTION_ID { get; set; }
    public string AUTHORIZATION_TYPE { get; set; }
    public string CONTROL_IDENT { get; set; }
    public string PERSON_CUSTOMER_ID1 { get; set; }
    public string PERSON_CUSTOMER_ID2 { get; set; }
    public string PERSON_CUSTOMER { get; set; }
    public string PERSON_DEPARTMENT { get; set; }
    public string PERSON_DEPARTMENT_ID { get; set; }
    public string PERSON_NAME { get; set; }
    public string PERSON_IDENT_NO { get; set; }
    public string PERSON_IDENT_DESC { get; set; }
    public string PERSON_1_CODE { get; set; }
    public string PERSON_2_CODE { get; set; }
    public string PERSON_3_CODE { get; set; }
    public string PERSON_4_CODE { get; set; }
    public string PERSON_5_CODE { get; set; }
    public string CAR_CUSTOMER_ID1 { get; set; }
    public string CAR_CUSTOMER_ID2 { get; set; }
    public string CAR_CUSTOMER { get; set; }
    public string CAR_DEPARTMENT { get; set; }
    public string CAR_DEPARTMENT_ID { get; set; }
    public string CAR_DESIGNATION { get; set; }
    public string CAR_DESCRIPTION { get; set; }
    public string CAR_IDENT_NO { get; set; }
    public string CAR_IDENT_DESC { get; set; }
    public string CAR_1_CODE { get; set; }
    public string CAR_2_CODE { get; set; }
    public string CAR_3_CODE { get; set; }
    public string CAR_4_CODE { get; set; }
    public string CAR_5_CODE { get; set; }
    public string TR_CODE1 { get; set; }
    public string TR_TEXT1 { get; set; }
    public string TR_CODE2 { get; set; }
    public string TR_TEXT2 { get; set; }
    public string TR_CODE3 { get; set; }
    public string TR_TEXT3 { get; set; }
    public string TR_CODE4 { get; set; }
    public string TR_TEXT4 { get; set; }
    public string ISSUED_BY { get; set; }
    public string CASH_DESK { get; set; }
    public string SHIFT { get; set; }
    public string TRANSACTION_ID_DISP { get; set; }
    public string DISPENSER { get; set; }
    public string NOZZLE { get; set; }
    public string TANK { get; set; }
    public string PRODUCT_ID { get; set; }
    public string PRODUCT { get; set; }
    public string PRODUCT_1_CODE { get; set; }
    public string PRODUCT_2_CODE { get; set; }
    public string PRODUCT_3_CODE { get; set; }
    public string PRODUCT_4_CODE { get; set; }
    public string PRODUCT_5_CODE { get; set; }
    public string AMOUNT { get; set; }
    public string UNIT { get; set; }
    public string UNIT_PRICE_NO_VAT { get; set; }
    public string TOTAL_PRICE_NO_VAT { get; set; }
    public string UNIT_PRICE_VAT { get; set; }
    public string TOTAL_PRICE_VAT { get; set; }
    public string VAT_RATE { get; set; }
    public string CURRENCY { get; set; }
}